/* ***************** *
 *   ACTION TYPES    *
 * ***************** */

export enum ActionTypes {
  ACTIVITIES = '@COUNSELOR/ACTIVITIES',
  DASHBOARD = '@COUNSELOR/DASHBOARD',
  STUDENTS = '@COUNSELOR/STUDENTS',
  STUDENTS_PROFILE = '@COUNSELOR/STUDENT_PROFILE',
  METRICS = '@COUNSELOR/METRICS',
  MOOD_CHECK_IN = '@COUNSELOR/MOOD_CHECK_IN',
  NOTIFICATIONS = '@COUNSELOR/NOTIFICATIONS',
}
