/* ***************** *
 *   ACTION TYPES    *
 * ***************** */

export enum ActionTypes {
  ACTIVITIES = '@COUNSELOR/ACTIVITIES',
  DASHBOARD = '@COUNSELOR/DASHBOARD',
  STUDENTS = '@COUNSELOR/STUDENTS',
  STUDENTS_PROFILE = '@COUNSELOR/STUDENT_PROFILE',
  METRICS = '@COUNSELOR/METRICS',
  MOOD_CHECK_IN = '@COUNSELOR/MOOD_CHECK_IN',
  NOTIFICATIONS = '@COUNSELOR/NOTIFICATIONS',

  // REQUEST_BOOKING_DETAILS = '@COUNSELOR/REQUEST_BOOKING_DETAILS',
  // POLL_BOOKING_DETAILS = '@COUNSELOR/POLL_BOOKING_DETAILS',
  // MY_BOOKING_ERROR = '@COUNSELOR/MY_BOOKING_ERROR',
  // MY_BOOKING_PENDING = '@COUNSELOR/MY_BOOKING_PENDING',
  // REQUEST_BOOKING_DETAILS_SUCCESS = '@COUNSELOR/REQUEST_BOOKING_DETAILS_SUCCESS',
  // RESET_BOOKING_DETAILS = '@COUNSELOR/RESET_BOOKING_DETAILS',
  // RESET_BOOKING_PENDING = '@COUNSELOR/RESET_BOOKING_PENDING',
  // RESET_BOOKING_ERROR = '@COUNSELOR/RESET_BOOKING_ERROR',
  // SET_BOOKING_ID = '@COUNSELOR/SET_BOOKING_ID'
}
