name: Deploy Preview (Vercel)

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - name: Run checks
        run: |
          yarn format:fix
        working-directory: ${{ inputs.WORKING_DIRECTORY }}